flow generator
hantman-lab/animal-soup pull request #18
Opened 2023-07-15 14:24 UTC by clewis7

start incorporating flow generator 

current idea: 
- use pre-trained weights from ground truth
- train flow gen using `df.flow_generator.train()`
    -  have default model args, but can be user updated

2023-07-16 00:51 UTC, clewis7 commented
TODO/Ideas
- [ ] way to have dataset, dataloader based on entries in dataframe
    - for now will be passing in combined movies, in the future will need to do combination on the fly
- [ ] set default augs, how much should users have control over model params? (initial learning rate, batch size, mode)
- [ ] add final model params to dataframe
- [ ] model output columns as well with useful info, perhaps epoch losses 
- [ ] save model weights as checkpoint when training is finished to the same location as the dataframe
- [ ] save all other relevant output information in hdf5 file
- [ ] during training...tqdm to show progress, but also matplotlib to plot losses of each epoch? or just save losses to output to plot later (user might not care about)

2023-07-18 06:08 UTC, kushalkolar requested changes

2023-07-18 06:08 UTC, kushalkolar commented on animal_soup/viewers/__init__.py
> +from ._ethogram_comparison import EthogramComparison
append Viz to each so we know it's a viz module, unify names

2023-07-18 12:50 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        model = self._load_pretrained_model(weight_path=Path('/home/clewis7/repos/animal-soup/pretrained_checkpoints/flow_gen.ckpt'), mode="slow")
yeah, Stefan and I talked about this some...I think there is no need to have the DEG model weights...only cj-model weights once we have trained with ground truth and use that as the default model weights

but then if someone wants to retrain, then the new model weights will get saved and those can become the default for that dataframe

need to think about how to make it easy for a user to use what checkpoint for the model weights, default should def be cj-weights, but then changing it after that

2023-07-18 12:51 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +            # for now assuming codec is AVI, but in future will need to detect or update
yeah, had thought about this...either user needs to specify codec or need someway to detect what codec a video is...I think glob for all could be okay

2023-07-18 12:52 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +            training_vids.append(parent_data_path.joinpath(row["animal_id"],
hmm, I think it would be useful but then also make the dataframe a little messier visually....

2023-07-18 12:54 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        # in notes column, add flow_gen_train params for model
yeah, something like this...Stefan and I talked about how people in the lab will prob only want to specify the mode and perhaps something like batch size...but beyond that most thing should be default and then we could just expose them in a column

2023-07-18 12:55 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        return model
yeah, I was just returning the model here for testing purposes to make sure the model had the weights from the checkpoint!! still very alpha lol

2023-07-18 12:57 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        pretrained_model_state = new_state_dict
some of the checkpoint have this weird 'model.' pre-pended to the layer weights and they  need to be the same as what the model you are trying to update the weights to will be...this is how DEG was doing it, but I am sure there is something better

2023-07-18 12:58 UTC, clewis7 commented on animal_soup/__init__.py
> +from .flow_generator import *
yeah, was just a placeholder for type annotation where I was returning the model, but that is going to change

2023-07-18 13:12 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +            | learning_rate | Stop training when learning rate drops below a given threshold             |
this is how DEG defines it 

```
"""Simple early stopper that stops when the learning rate drops below some threshold.
    Example usage: you reduce your learning rate when your validation loss stops improving. If the learning rate drops
        below some minimum value, automatically stop training.
```

2023-07-18 21:20 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        model = self._load_pretrained_model(weight_path=Path('/home/clewis7/repos/animal-soup/pretrained_checkpoints/flow_gen.ckpt'), mode="slow")
model in/model out kwargs

default is pretrained cj-weighs, unless otherwise specified by model Path kwargs

2023-07-18 21:26 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        pretrained_model_state = new_state_dict
use lstrip() instead

2023-07-19 12:54 UTC, clewis7 commented
closes #23

2023-07-19 20:43 UTC, clewis7 commented
THINGS LEFT TO DO FOR FLOW GEN:
- [ ] finish lightning module
    - [ ] finish implementing loss 
    - [ ] implement image reconstructor
    - [ ] finish implementing step process for model
- [ ] implement trainer using lightning module
- [ ] train DEG with ground truth data with each model to get checkpoints
- [ ] add column to dataframe for model params and save to disk

THINGS TO THINK ABOUT:
1. DEG does a lot of metric computations, what is sufficient for us? 
    - my current thoughts are to just calculate the batch loss through every epoch and at the end of each epoch plot the loss and output
    - DEG uses SSIM flow metric also for flow gen in addition to loss
2. What information should be being saved to output file? What is actually relevant to people in the lab? 
3. Should we save the checkpoint at every epoch for safety purposes? 

@kushalkolar thoughts?

2023-07-24 07:07 UTC, kushalkolar requested changes

2023-07-24 07:07 UTC, kushalkolar commented on animal_soup/flow_generator/train.py
> +        weight_decay = 0  # if self.hparams.weight_decay is None else self.hparams.weight_decay
what's the commented out code??

2023-07-24 07:07 UTC, kushalkolar commented on animal_soup/flow_generator/train.py
> +    tensorboard_logger = pl.loggers.tensorboard.TensorBoardLogger(
run `black` on the codebase

2023-07-24 07:07 UTC, kushalkolar commented on animal_soup/utils/callbacks.py
> +    def on_train_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
does this work as expected?

2023-07-24 07:07 UTC, kushalkolar commented on animal_soup/utils/transforms.py
> +"""Utility functions and classes for getting transformations or applying them."""
this is just directly taken from DEG right? Put a link.

2023-07-24 07:07 UTC, kushalkolar commented on setup.py
> +    "omegaconf",
put a comment for any "non obvious" dependencies, because we will forget why stupid ones like this are here when it's not used anywhere

2023-07-24 12:11 UTC, clewis7 commented on animal_soup/data/datasets.py
> +    """PyTorch Dataset for loading a set of sequential frames and applying pre-defined augmentations to each frame."""
yes, one of the augmentations is jittering the color, which takes into account brightness, contrast, saturation, and hue

2023-07-24 12:22 UTC, clewis7 commented on animal_soup/data/datasets.py
> +                self._zeros_image[i, ...] = self.mean_by_channels[i]
yeah, this is what gets calculated in the normalization augmentation and then you can use the mean by channel to normalize images across your dataset

2023-07-24 12:26 UTC, clewis7 commented on animal_soup/data/datasets.py
> +        seed = np.random.randint(2147483647)
The append/prepend does not happen until you call `__get_item__`, and I think setting the seed makes sure things remain consistent if you call `__get_item__` more than once...not sure why they did this

2023-07-24 12:27 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +              flow_window: int = 11,
yeah, I think they use 11 as a general but because our task is so specific that maybe decreasing this would be okay

2023-07-24 12:27 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +            Window size for computing optical flow features of a frame. Recommended to be the minimum number of frames
yes, but I did not implement it...I can though

2023-07-24 12:28 UTC, clewis7 commented on animal_soup/extensions/flow_gen_extensions.py
> +        if model_in is not None:
that is because it gets parsed later in loading the model from a checkpoint if model in is `None`

2023-07-24 12:41 UTC, clewis7 commented on animal_soup/utils/callbacks.py
> +    def on_train_epoch_end(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
yes!!

2023-07-24 12:43 UTC, clewis7 commented on animal_soup/flow_generator/train.py
> +        weight_decay = 0  # if self.hparams.weight_decay is None else self.hparams.weight_decay
irrelevant, you can have weight decay as a param but then DEG just uses zero no matter what

2023-07-24 12:45 UTC, clewis7 commented on animal_soup/flow_generator/train.py
> +        else:  # no need to validate because model weights will have already been loaded
that there is no need to validate the `model_in` path again here because it will have already been validated when loading in the model weights

2023-07-24 14:51 UTC, merged

2023-07-24 19:26 UTC, kushalkolar commented on animal_soup/flow_generator/train.py
> +        weight_decay = 0  # if self.hparams.weight_decay is None else self.hparams.weight_decay
I guess it's a carried over comment from DEG code? I'd just delete it because it's confusing like why is this there