implement CI for test suite
hantman-lab/animal-soup pull request #22
Opened 2023-07-16 13:39 UTC by clewis7

2023-07-16 14:18 UTC, clewis7 commented
```
ERROR: file:///home/runner/work/animal-soup/animal-soup does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
continuing error, I do not understand...there is a `setup.py` file

2023-07-16 14:22 UTC, clewis7 commented
does the package need to be published on pypi first? I thought cloning the repo would alleviate this issue...

2023-07-16 14:37 UTC, clewis7 commented
new problem: tests not being found

2023-07-18 06:23 UTC, kushalkolar requested changes

2023-07-18 06:23 UTC, kushalkolar commented on .github/workflows/ci.yml
> +        pip install git+https://github.com/hantman-lab/animal-soup.git
This isn't useful, you want to test the current commit state that has been pulled in. This will pull the latest from github.

2023-07-18 06:23 UTC, kushalkolar commented on .gitignore
> +animal_soup/tests/ground_truth.zip
I think you can do `test/*.zip`

2023-07-18 06:23 UTC, kushalkolar commented on animal_soup/ethogram_utils.py
where's this been moved to?

2023-07-18 06:23 UTC, kushalkolar commented on animal_soup/tests/__init__.py
you shouldn't put tests in the package source tree, it was correct before in the root

2023-07-18 06:23 UTC, kushalkolar commented on animal_soup/tests/test_soup.py
you shouldn't put tests in the package source tree, it was correct before in the root

2023-07-18 06:23 UTC, kushalkolar commented on .github/workflows/ci.yml
> +            pyversion: '3.10'
Just do py311 since this is a lab project, if it expands py39 will be deprecated by then. Error messages are much nicer in py311 so it's better for the lab.

2023-07-18 06:23 UTC, kushalkolar commented on .github/workflows/ci.yml
I don't know if github actions has GPUs that you can use to test the GPU dependent code. I also think CI with that would be difficult, since SGD is inherently going to give different results each time. You could run tests on github actions that check everything else, and for GPU specific stuff (like to make sure training and inference etc. is functional) run that locally and produce plots to see if they look right? (loss, and diffs of predictions vs. ground predictions that you have had before).

2023-07-18 12:39 UTC, clewis7 commented on .github/workflows/ci.yml
yeah, thinking about how to test those things will take some more thought I think, I like the plots idea...can maybe brainstorm some other ideas too

2023-07-18 12:41 UTC, clewis7 commented
yay!

2023-07-19 12:35 UTC, merged