feature extractor
hantman-lab/animal-soup pull request #33
Opened 2023-07-24 18:45 UTC by clewis7

implementing training and inference using feature extractor

2023-07-24 19:42 UTC, kushalkolar requested changes

2023-07-24 19:42 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +            | stop method   | description                                                                |
"early" not in table

2023-07-24 19:42 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +            stored in the same directory as the dataframe.
maybe rename these to something like `"flow_model"`, `"feature_model_in"`, `"feature_model_out"`?

2023-07-26 08:08 UTC, kushalkolar requested changes

2023-07-26 08:08 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if len(list(set(list(self._df["exp_type"])))) != 1:
wat, how did you end up with this O_O

Just use:

```python
if np.unique(df["exp_type"].values).size > 1
```

2023-07-26 08:08 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if list(set(list(self._df["exp_type"])))[0] is None:
Is this to check if any row has `exp_type` == `None`? Should also check for nan. Anyways, if so this is not the right way to check.

2023-07-26 08:08 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if list(set(list(self._df["exp_type"])))[0] is None:
I think `if None in np.unique(df["exp_type"].values)` might work. 

If not then this will work:

```python
if None in np.unique(df["exp_type"].values).tolist()
```

2023-07-26 08:08 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if batch_size < MIN_BATCH_SIZE or batch_size > MAX_BATCH_SIZE:
python lets you have expressive math operators :smile: , so you can just do:

```python
if not MIN_BATCH_SIZE < batch_size < MAX_BATCH_SIZE:
```

2023-07-26 11:38 UTC, clewis7 commented on animal_soup/data/datasets.py
> +        if labels is None: # non supervised training
if you are doing flow generator training than that is unsupervised

2023-07-27 05:34 UTC, kushalkolar requested changes

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/data/utils.py
> +        # for that time point
explain this better, sum across all behaviors at a given timepoint, if the sum is `0`, set `background = 1`

How fast is this when you have hundreds of ethograms? It's looks like a relatively slow for loop, but it might be more than sufficient for this use case.

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/data/datasets.py
> +                self.pos_weight = make_loss_weight(self.num_pos, self.num_neg)
what's `pos_weight`? more useful name?

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +            reconstructed.
I don't understand what happens when the default is `None`?

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +                                 "{'slow': 'TinyMotionNet3D', 'medium': 'MotionNet', 'fast': 'TinyMotionNet}")
the braces `{` are not necessary here in just an error message :smile:

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if len(set(self._df["exp_type"].values)) > 1:
does `np.unique()` not work here? It should since `.values` returns a 1d numpy array.

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        One of [ResNet18, ResNet50, ResNet34-3D]. Depends on mode. Either a flow classifier or a spatial classifier.
put mode inside double backticks so it's formats distinctly in the docs

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        One of ["average", "weighted_average", "concatenate"]. Indicates the way that fusing the classifier
this isn't necessary for the user since this is a private method, but I'm curious what's the difference between these fusion types?

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/feature_extractor/inference.py
what's the point of this file?

2023-07-27 05:34 UTC, kushalkolar commented on animal_soup/utils/defaults.py
A dict of dicts like this gets very messy to read. I would make a yaml file and read that yaml in as a dict.

2023-07-27 19:41 UTC, merged

2023-07-27 23:00 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if len(set(self._df["exp_type"].values)) > 1:
That's wird I'm curious, what did you get?

2023-07-28 00:10 UTC, kushalkolar commented on animal_soup/feature_extractor/inference.py
> +        # and use this to store into our buffer in the right location
can you come up with a test that checks that this works correctly?

2023-07-28 13:33 UTC, clewis7 commented on animal_soup/extensions/feature_extr_extensions.py
> +        if len(set(self._df["exp_type"].values)) > 1:
part of `np.unique` is that it does some kind of ordering, and so if there is `None` in the unique values...it was giving error because it was trying to order a `str` and `None` type

2023-07-28 13:36 UTC, clewis7 commented on animal_soup/data/datasets.py
> +class VideoIterable(data.IterableDataset):
the video files in DEG remain with whatever codec they originally were, the hdf5 files are for storing outputs not anything to do with the videos

2023-07-28 13:37 UTC, clewis7 commented on animal_soup/extensions/feature_extr_extensions.py
> +            gpu_transform=get_gpu_inference_transforms(AUGS, conv_mode=conv_mode)
for gpu inferences you just convert to float and normalize, cpu transforms you just crop and resize

2023-07-28 13:38 UTC, clewis7 commented on animal_soup/feature_extractor/inference.py
> +        GPU augmentations. For inference, should just be conversion to float and z-scoring, by default None
oh, shouldn't be optional...think that was left over doc string from deg I need to fix

2023-07-28 13:38 UTC, clewis7 commented on animal_soup/feature_extractor/inference.py
> +        # and use this to store into our buffer in the right location
yeah, I think next week I will spend some time working on testing

2023-07-29 02:29 UTC, kushalkolar commented on animal_soup/extensions/feature_extr_extensions.py
> +        if len(set(self._df["exp_type"].values)) > 1:
ah interesting thanks! Now I know of a usecase where `set` works but `np.unique` doesn't :smile: . So I guess in this case the `.values` returns an array with `dtype` `object` instead of `str` since it's mixed types.

2023-07-29 02:30 UTC, kushalkolar commented on animal_soup/feature_extractor/inference.py
> +        GPU augmentations. For inference, should just be conversion to float and z-scoring, by default None
ah so basically zscore is necessary for it to work properly I guess? makes sense because zscoring is often required preprocessing for any type of classification