update to concat frames
hantman-lab/animal-soup pull request #45
Opened 2023-08-03 19:58 UTC by clewis7

2023-08-08 22:00 UTC, clewis7 commented
for now the solution for feature extractor inference loading is to just not use multiprocessing for loading in frames until I can investigate it more and figure out how to make it work with two videos where you are not necessarily getting the same frames from the workers 

but, I tried out inference with sample data and it worked wonders...going to try with yuechen's data as well

2023-08-09 08:52 UTC, kushalkolar requested changes
Thoughts:

1. Does the parallel reading of vids work at all? If so can you come up with a sanity check test? 
2. If not, how much slower is training and inference? 
3. If the parallel reading works, benchmark for the optimal `num_workers`
4. For the ground truth dataset which already has concated vids, I would just split them into side and front vids if you need to train new models with that dataset. MUCH easier than trying to have an implementation that works for both concat and pre-concat vids!

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/behavior_extensions.py
>                          f"Item already exists with animal_id={animal_id}, "
see newlines newlines

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/behavior_extensions.py
> +                }
seems like this block is very repetitive, I've seen it 3 times. Can you make a function for it?

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/behavior_extensions.py
> +                }
This along with the previous sanity check that raises too

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/behavior_extensions.py
> +                        "vid_paths": vid_paths,
This entire block is also repetitve, see if possible to abstract away into a function

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/sequence_extensions.py
> +                if str(self._series["trial_id"]) not in f.keys():
it doesn't matter in this case, but with pandas series you can also do things like:

```python
series["column"].astype(str)
```

more useful if you have a dataframe and want it for an entire column like:

```python
df["trial_id"].astype(str)
```

or if you need different numpy dtypes, like `float32` etc.

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/sequence_extensions.py
> +                features["flow_features"] = f[str(self._series["trial_id"])]["features"]["flow"][:]
I would assign a var like `curr_trial`, much more readable than this because it has lots of indexing

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/extensions/sequence_extensions.py
> +            if "sequence" in f[str(self._series["trial_id"])].keys():
just get curr_trial once so you don't need this indexing all the time, makes it more readable :D

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/feature_extractor/inference.py
> +        num_workers: int = 0,
does it work with > 0 ? even numbers?

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/feature_extractor/inference.py
> +    dataset = VideoIterable(vid_path,
no longer necessary to stringify the `Path` ?

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/utils/z_score.py
> +    for i in tqdm(range(0, min(len(left_reader), len(right_reader)), stride)):
difficult to read, take assign the `min()` call to `n_frames` so it's just `range(0, n_frames, stride)`

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/viewers/_behavior.py
> +                self.image_widget = ImageWidget(data=data, ctx=gpu_context(0),
decord context is given to `LazyVideo` not `ImageWidget` :joy:

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/viewers/_behavior.py
> +                    data=data,
this else block isn't necessary, decord context is for lazyvideo not image widget

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/viewers/ethogram_utils.py
> +        if str(row["trial_id"]) not in f.keys():
assign `curr_trial` reference and use it, more readable than lots of indexing throughout

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/viewers/ethogram_utils.py
> +            return f[str(row["trial_id"])]["ethograms"]["cleaned_ethogram"][:]
assign `curr_trial` reference and use it, more readable than lots of indexing throughout

2023-08-09 08:52 UTC, kushalkolar commented on animal_soup/viewers/ethogram_utils.py
> +        if "cleaned_ethogram" in f[str(row["trial_id"])]["ethograms"].keys():
assign `curr_trial` reference and use it, more readable than lots of indexing throughout

2023-08-09 08:52 UTC, kushalkolar commented on docs/source/user_guide.rst
> +    For each trial, there should be a front and side video that will get concatenated together for you during inference
add: _"on the fly"_

2023-08-09 14:07 UTC, clewis7 commented
need to think more about allowing multiprocessing frame reading for feature extractor inference....I think I can figure it out just need to understand more about how pytorch IterableDataset works

2023-08-10 14:25 UTC, merged