store features and ethograms by mode
hantman-lab/animal-soup pull request #57
Opened 2023-09-18 13:34 UTC by clewis7

closes #43

2023-09-18 15:12 UTC, clewis7 commented
https://github.com/hantman-lab/animal-soup/assets/69729525/fa478da5-75b8-4442-b322-f99e24910d06

2023-09-18 15:13 UTC, clewis7 commented
Can now toggle between modes of inference, makes it to where features and ethograms are not overwritten every time you run inference 

If inference for a `mode` has not been run, will simply display a blank plot

2023-09-19 03:37 UTC, kushalkolar requested changes

2023-09-19 03:37 UTC, kushalkolar commented on animal_soup/extensions/sequence_extensions.py
> +                features["flow_features"] = f[curr_trial][mode]["features"]["flow"][:]
a cleaner way to write this might be:

```python
group = f"{curr_trial}/{mode}/features"
for k in ["logits", "probabilities", "spatial_features", "flow_features"]:
  features[k] = f[group][k][:]
```

Untested but I think this should work, in h5py you can use `"level_1/level_2/...level_n"` instead of `["level_1"]["level_2"]...["level_n"]`

2023-09-19 03:37 UTC, kushalkolar commented on animal_soup/viewers/_ethogram.py
> +                      f'chew: 0',
wouldn't `None` be better to display than 0 for each if the ethogram does not exist?

2023-09-19 03:37 UTC, kushalkolar commented on animal_soup/viewers/_ethogram_cleaner.py
> +        # allows for toggling between modes without throwing errors
is the plot cleared anywhere to make sure it goes empty?

2023-09-23 23:09 UTC, merged