refactor cleaning ethograms to use keyboard events
hantman-lab/animal-soup pull request #9
Opened 2023-06-19 17:52 UTC by clewis7

2023-06-19 17:54 UTC, clewis7 commented
@kushalkolar thoughts?

2023-06-20 03:13 UTC, kushalkolar requested changes

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +HIGHLIGHT_GRAPHICS = ["lift_highlight", "handopen_highlight", "grab_highlight", "sup_highlight", "atmouth_highlight",
one per line is easier to read

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +            # check if clean_df exists and user didn't
and user didn't what?

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
>  class EthogramCleaner(EthogramVizContainer):
docstring

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
>  class EthogramCleaner(EthogramVizContainer):
do you have pycharm setup to make it automatically?

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +        if obj.key == 's':
comments for every if else claus, this is unreadable

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +        current_behavior_name = self.currently_selected_behavior.name.split('_')[0]
This is so much easier if you make a `@property` for `selected_behavior`.

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +        if obj.key == 's':
I'm really having a hard time parsing out this entire if else block

2023-06-20 03:13 UTC, kushalkolar commented on animal_soup/_ethogram_cleaner.py
> +    def reset_ethogram(self):
do you want to have the option to reset only for the current behavior vs. entire ethogram?

2023-06-20 11:55 UTC, clewis7 commented on animal_soup/_ethogram_cleaner.py
> +    def reset_ethogram(self):
yeah, I think that would be a good idea, will add that in

2023-06-21 13:26 UTC, merged